### ISSUE TITLE
[At/Before May 1st] -- PayPal's BrainTree Notice To Customers

### ISSUE THREAD

**Issue by irwin-nikk** [invainn/ARIA#184]
In the Register for an Event stepper, we need to have a notice to customers which both informs them about the Drop-In UI and helps them trust the implementation by educating them about PayPal's BrainTree service, how it works, and why it can/should be trusted. This disclaimer should appear in below the Drop-In UI.

**Comment by Kevin-Carlos** [comment]
@irwin-nikk  @invainn 

* This issue cannot be resolved until BrainTree is hooked up to the server for authentication. 
I cannot add a button/popover/tooltip for BrainTree as this is a stateless function and "hooking" state into it for a button is not working and the component will need to be changed to a stateful component anyhow to pull and send client authentication tokens to our server.

Because of this, I will not jank my way to adding this feature.

**Comment by invainn** [comment]
@Kevin-Carlos I appreciate you not trying to "jank your way" adding the feature.

State management regarding transactions related to Braintree will be handled by Redux when the backend is configured properly.

I will look more into this.
